---
title: "New DATES"
author: "Nataly Romero"
date: "2023-05-20"
output: html_document
---
#Tipo de organos legislativos 
```{r}
library(rvest)
url = "https://datos.bancomundial.org/indicator/IT.NET.USER.ZS?end=2019&start=2019&view=map"
fullxpath = "/html/body/div[1]/div/main/div[3]/div/div[1]/section[2]/table[2]"
url = read_html(url)
table = html_nodes(url, xpath= fullxpath)
table = html_table (table)
table = data.frame(table)
```


```{r}
library(openxlsx)
tablaLEGIS <-table
write.xlsx(tablaLEGIS, "tablaLEGIS.xlsx")
```
#Base Internet 
```{r}
library(rvest)
url = "https://datos.bancomundial.org/indicator/IT.NET.USER.ZS?end=2019&start=2019&view=map"
fullxpath = "/html/body/div[1]/div/div/div/div[3]/div/div/article/section/div/div/div/section/div/div[2]/div[1]"
url = read_html(url)
table = html_nodes(url, xpath= fullxpath)
table = html_table (table)
table = data.frame(table)
```
```{r}
library(openxlsx)
tablaIntx <-table
write.xlsx(tablaIntx, "tablaIntx.xlsx")
```


#Libertad de prensa

```{r}
library(rvest)
url = "https://es.m.wikipedia.org/wiki/%C3%8Dndice_de_libertad_de_prensa"
fullxpath = "/html/body/div[1]/div/main/div/div/div/div/div[4]/div[1]/div[2]/div[3]https://rsf.org/es/clasificacion?year=2019"
url = read_html(url)
table = html_nodes(url, xpath= fullxpath)
table = html_table (table)
table = data.frame(table)
```


```{r}
library(openxlsx)
tablaFree <-table
write.xlsx(tablaFree, "tablaFree.xlsx")
```

#PBI per país (DEL BANCO MUNDIAL)
```{r}
library(rvest)
url = "https://datos.bancomundial.org/indicator/NY.GDP.MKTP.CD?end=2019&start=2019&view=map"
fullxpath = "/html/body/div[1]/div/div/div/div[3]/div/div/article"
url = read_html(url)
table = html_nodes(url, xpath= fullxpath)
table = html_table (table)
table = data.frame(table)
```

```{r}
library(openxlsx)
tablaPBBI <-table
write.xlsx(tablaPBBI, "tablaPBBI.xlsx")
```

#FUERZAS ARMADAS 

```{r}
library(rvest)
url = "https://datos.bancomundial.org/indicator/MS.MIL.TOTL.P1?end=2019&start=2019&view=map"
fullxpath = "/html/body/div[1]/div/div/div/div[3]/div/div/article"
url = read_html(url)
table = html_nodes(url, xpath= fullxpath)
table = html_table (table)
table = data.frame(table)
```

```{r}
library(openxlsx)
tablaARM <-table
write.xlsx(tablaARM, "tablaARM.xlsx")
```
